### ISSUE TITLE
[Bug] Library is not working in go 1.21

### ISSUE THREAD

**Issue by ovechkin-dm** [timandy/routine#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue reproduce with the latest release?

- [X] I have upgrade to the latest version

### Steps To Reproduce

Library is not working as expected on 1.21.
Tests from this library are failing: 

```
go test ./...
*** GOOS: darwin ***
*** GOARCH: arm64 ***
#numField: 50
#offsetGoid: 152
#offsetPaniconfault: 181
#offsetGopc: 280
#offsetLabels: 344
--- FAIL: TestObject (0.00s)
thread_local_map_test.go:13:
Error Trace:	./thread_local_map_test.go:13
Error:      	Expected and actual point to the same object: 0x10503ef00 &routine.object{}
Test:       	TestObject
FAIL
FAIL	github.com/timandy/routine	3.298s
ok  	github.com/timandy/routine/g	(cached)
FAIL 
```

Also output of tests on Linux, AMD64:

```
go test ./...


--- FAIL: TestFutureTask_Routine_Complete (0.87s)
panic: RuntimeError: Task execution timeout after 100ms.
   at github.com/timandy/routine.(*futureTask).timeout() in /home/dovechkin/workspace/routine/future_task.go:116
   at github.com/timandy/routine.(*futureTask).GetWithTimeout() in /home/dovechkin/workspace/routine/future_task.go:92
   at github.com/timandy/routine.TestFutureTask_Routine_Complete() in /home/dovechkin/workspace/routine/future_task_test.go:497
   at testing.tRunner() in /usr/local/go/src/testing/testing.go:1595
   --- End of error stack trace ---
   created by testing.(*T).Run() in /usr/local/go/src/testing/testing.go:1648 [recovered]
        panic: RuntimeError: Task execution timeout after 100ms.
   at github.com/timandy/routine.(*futureTask).timeout() in /home/dovechkin/workspace/routine/future_task.go:116
   at github.com/timandy/routine.(*futureTask).GetWithTimeout() in /home/dovechkin/workspace/routine/future_task.go:92
   at github.com/timandy/routine.TestFutureTask_Routine_Complete() in /home/dovechkin/workspace/routine/future_task_test.go:497
   at testing.tRunner() in /usr/local/go/src/testing/testing.go:1595
   --- End of error stack trace ---
   created by testing.(*T).Run() in /usr/local/go/src/testing/testing.go:1648

goroutine 4349 [running]:
testing.tRunner.func1.2({0x5e8b40, 0xc000100190})
        /usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x5e8b40?, 0xc000100190?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/timandy/routine.(*futureTask).GetWithTimeout(0xc000a26200, 0x4d5000?)
        /home/dovechkin/workspace/routine/future_task.go:97 +0x1f5
github.com/timandy/routine.TestFutureTask_Routine_Complete(0xc000a0eb60?)
        /home/dovechkin/workspace/routine/future_task_test.go:497 +0x84
testing.tRunner(0xc000a0ed00, 0x635ab8)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad
FAIL    github.com/timandy/routine      25.452s
ok      github.com/timandy/routine/g    1.737s
FAIL
```

### Expected Behavior

Library tests should pass

### Current Behavior

Library tests are failing

### Environment

go 1.21 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@ovechkin-dm Thanks for your report, I am looking at this problem.

**Comment by timandy** [comment]
Hello @ovechkin-dm 
Could you re-run the test with the commit-version `b70d1ad48cc7da813acee30f5b093f091be83b75`

**Comment by timandy** [comment]
@ovechkin-dm  ping

**Comment by timandy** [comment]
Long time no response, I will clos it.
If have any questions. Please reopen this issue.
