### ISSUE TITLE
TestPProf会报错

### ISSUE THREAD

**Issue by liangmanlin** [timandy/routine#9]
```golang
func TestPProf(t *testing.T) {
	const concurrency = 100
	const loopTimes = 10000
	tls := NewThreadLocal()
	tls.Set("你好")
	wg := &sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		tmp := i
		go func() {
			for j := 0; j < loopTimes; j++ {
				time.Sleep(10 * time.Millisecond)
				tls.Set(tmp)
				assert.Equal(t, tmp, tls.Get())
				pprof.Do(context.Background(), pprof.Labels("key", "value"), func(ctx context.Context) {
					tls.Set("hi")
					label, find := pprof.Label(ctx, "key")
					assert.True(t, find)
					assert.Equal(t, "value", label)
					//
					//assert.Nil(t, currentThread(false))
					//assert.Nil(t, tls.Get())
					//tls.Set("hi")
					assert.Equal(t, "hi", tls.Get())
					//
					label2, find2 := pprof.Label(ctx, "key")
					assert.True(t, find2)
					assert.Equal(t, "value", label2)
				})
				assert.Nil(t, tls.Get())
			}
			wg.Done()
		}()
	}
	assert.Nil(t, pprof.StartCPUProfile(&bytes.Buffer{}))
	wg.Wait()
	pprof.StopCPUProfile()
	assert.Equal(t, "你好", tls.Get())
}
```

使用上述测试代码，发现偶发如下报错

```bash
[root@ routine]# go test -run TestPProf
unexpected fault address 0x5f87cb
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5f87cb pc=0x598424]

goroutine 27 [running]:
runtime.throw({0x5f8c17?, 0xc00017f828?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000328d58 sp=0xc000328d28 pc=0x436dd1
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc000328da8 sp=0xc000328d58 pc=0x44cdc5
github.com/timandy/routine.(*threadLocalMap).set(...)
        /mnt/hgfs/go/routine/thread_local_map.go:24
github.com/timandy/routine.(*threadLocal).Set(0xc00005d400, {0x5bf720?, 0x6400b0})
        /mnt/hgfs/go/routine/thread_local.go:36 +0x64 fp=0xc000328de0 sp=0xc000328da8 pc=0x598424
github.com/timandy/routine.TestPProf.func1.1({0x641c40, 0xc000351ce0})
        /mnt/hgfs/go/routine/thread_test.go:34 +0x69 fp=0xc000328e70 sp=0xc000328de0 pc=0x5a98e9
runtime/pprof.Do({0x641bd0?, 0xc0000160c0?}, {{0xc00032ea40?, 0x742a98?, 0x5bee20?}}, 0xc000328fb0)
        /usr/local/go/src/runtime/pprof/runtime.go:40 +0xa3 fp=0xc000328ee0 sp=0xc000328e70 pc=0x5092e3
github.com/timandy/routine.TestPProf.func1()
        /mnt/hgfs/go/routine/thread_test.go:33 +0xe7 fp=0xc000328fe0 sp=0xc000328ee0 pc=0x5a95a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000328fe8 sp=0xc000328fe0 pc=0x4681e1
created by github.com/timandy/routine.TestPProf
        /mnt/hgfs/go/routine/thread_test.go:28 +0x8e
```

在windows平台不会发生

go1.18.1

目前可以猜测的是，`thread`经过gc后，是没有重置数据的

我提了一个pr，你可以看看这样处理是否可以解决

**Comment by timandy** [comment]
我发现只要注册了 `runtime.SetFinalizer`，析构函数不执行任何代码，就不再引发 `fault error` 了。可能是 go1.18  sdk 的问题。

**Comment by liangmanlin** [comment]
> 我发现只要注册了 `runtime.SetFinalizer`，析构函数不执行任何代码，就不再引发 `fault error` 了。可能是 go1.18 sdk 的问题。

也有可能是新的GC策略，没细研究

**Comment by timandy** [comment]
@liangmanlin 请把 commit message 改成英文吧，参考以前的提交记录规范。

**Comment by liangmanlin** [comment]
看看？我也不懂

**Comment by timandy** [comment]
OK，测试通过会合并入主分支，提交记录我会重新整理下。

**Comment by timandy** [comment]
> 我发现只要注册了 `runtime.SetFinalizer`，析构函数不执行任何代码，就不再引发 `fault error` 了。可能是 go1.18 sdk 的问题。

这个是因为重置字段时，使用了闭包外的变量原因，使用参数的指针就正常了。此处仅做备忘说明，最新版已经无该问题。
``` go
func threadFinalize(t *thread) {
	runtime.SetFinalizer(t, func(p *thread) {
		t.magic = 0 //应该为 p.magic = 0
	})
}
```
